<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image pixelbin-lazyload <?= /** @escapeNotVerified */ $escaper->escapeHtmlAttr($block->getClass()) ?>"
    <?= $escaper->escapeHtml($block->getCustomAttributes()) ?>
    src="<?= /** @escapeNotVerified */ $block->getLazyloadPlaceholder() ?>"
    data-original="<?= $escaper->escapeUrl($block->getLazyloadPlaceholder()) ?>"
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" />
