<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>

<img class="photo image pixelbin-lazyload <?= $block->escapeHtmlAttr($block->getClass()) ?>"
    <?= $block->escapeHtml($block->getCustomAttributes()) ?>
    src="<?= $block->getLazyloadPlaceholder() ?>"
    data-original="<?= $block->escapeUrl($block->getLazyloadPlaceholder()) ?>"
    width="<?= $block->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $block->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" />
