<?php
/**
 * @var \Pixelbinio\Pixelbin\Block\System\Config\SyncButton $block
 */
?>
<?php
$pendingSyncCollection = $block->getPendingSyncCollection()->getSize();
?>
<div class="pp-buttons-container">
    <button
        id="<?= /** @escapeNotVerified */ $block->getId() ?>"
        type="button"
        onclick="window.location='<?= /** @escapeNotVerified */ $block->getAjaxCheckUrl() ?>'"
        class="action-default scalable primary ui-button ui-corner-all ui-widget"
        <?php if ($pendingSyncCollection>0): ?>
        disabled="disabled"
        <?php endif; ?>
    >
        <span>
            <span>
                <span><?= /** @escapeNotVerified */ $escaper->escapeHtml($block->getButtonLabel()); ?></span>
            </span>
        </span>
    </button>
</div>
<?php $syncCollection = $block->getTotalSyncCollection(); ?>
<?php if ($syncCollection->getSize() > 0): ?>
    <p><?= /** @escapeNotVerified */
        __("Total Media file %1", $syncCollection->getSize()) ?></p>
    <p><?= /** @escapeNotVerified */
        __("Total Media file synced %1", $block->getSuccessSyncCollection()->getSize()) ?></p>
    <p><?= /** @escapeNotVerified */
        __("Total Media file pending to sync %1", $pendingSyncCollection) ?></p>
    <p><?= /** @escapeNotVerified */
        __("Total Media file failed %1", $block->getFiledSyncCollection()->getSize()) ?></p>
<?php endif; ?>
