<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content */
?>
<?php
$pixelbinMLwidgetOprions = $block->getPixelbinMediaLibraryWidgetOptions();
?>

<div class="media-gallery-modal"
     data-mage-init='{"mediabrowser": <?= $escaper->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-action-buttons">
                    <?= $block->getButtonsHtml() ?>
                </div>
            </div>
        </div>
    </div>
    <div class="side-col">
        <div><?= $block->getChildHtml('wysiwyg_images.tree') ?></div>
    </div>
    <div class="main-col">
        <div id="error-message" data-action="show-error"></div>
        <?php if ($pixelbinMLwidgetOprions): ?>
            <button id="media_gallery_add_from_pixelbin_button"
                    title="<?= $escaper->escapeHtml(__('Add from Pixelbin')) ?>"
                    data-role="add-from-pixelbin-button"
                    type="button"
                    data-mage-init='{"pixelbinMediaLibraryModal":
                    <?= $escaper->escapeHtml($pixelbinMLwidgetOprions) ?>}'
                    class="action-secondary add-from-pixelbin-button pixelbin-button-with-logo lg-margin-bottom">
                <span><?= $escaper->escapeHtml(__('Add from Pixelbin')) ?></span>
            </button>
        <?php endif; ?>
        <div id="contents-uploader"
             class="contents-uploader"><?= $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
